name: CI
on:
  push:
  workflow_dispatch:

jobs:
  kernel:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
      with:
        repository: torvalds/linux
        fetch-depth: 1
    - run: sudo apt-get update && sudo apt-get -y install apt-utils bc lz4 binutils bison build-essential ca-certificates cscope debhelper dwarves flex gcc git libelf-dev libncurses-dev libssl-dev linux-source make openssl pahole perl-base pkg-config python3-debian python-is-python3 rsync vim
    - name: Configure
      run: |
        make defconfig
    - name: Build
      run: |
        make -j`nproc`
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.4
      with:
        name: bzImage
        path: arch/x86_64/boot/bzImage
  busybox:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - run: sudo apt-get update && sudo apt-get -y build-dep busybox
    - run: git clone https://git.busybox.net/busybox
    - run: |
      cd busybox
      make defconfig
      echo 'CONFIG_EXTRA_CFLAGS="-static"' >> .config
      make
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.4
      with:
        name: busybox
        path: busybox/busybox