name: Toybox Container
on:
  push:
  workflow_dispatch:

jobs:
  rootfs:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - run: |
          ./run-build-container.sh

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.4
      with:
        name: rootfs-initrd-kernel
        path: output/
