name: Toybox Container
on:
  push:
  workflow_dispatch:

jobs:
  rootfs:
    runs-on: ubuntu-24.04${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        runner: ["", "-arm"] #amd64 and arm
    steps:
    - uses: actions/checkout@v7
    - name: Collect Workflow Telemetry
      uses: fwilhe2/workflow-telemetry-action@v3
    - run: dpkg --print-architecture
    - run: |
          ./run-build-container.sh
          cp run-qemu${{ matrix.runner }}.sh output/
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v7.0.1
      with:
        name: rootfs-initrd-kernel${{ matrix.runner }}
        path: output/
