name: Kernel Matrix
on:
  push:
  workflow_dispatch:

jobs:
  kernel:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        kernel:
          - version: "6.11-rc6"
            source: "https://git.kernel.org/torvalds/t/linux-6.11-rc6.tar.gz"
          - version: "6.10.7"
            source: "https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.10.7.tar.xz"
          - version: "6.6.48"
            source: "https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.6.48.tar.xz"
          - version: "6.1.107"
            source: "https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.1.107.tar.xz"
          - version: "5.15.165"
            source: "https://cdn.kernel.org/pub/linux/kernel/v5.x/linux-5.15.165.tar.xz"
          - version: "5.10.224"
            source: "https://cdn.kernel.org/pub/linux/kernel/v5.x/linux-5.10.224.tar.xz"
          - version: "5.4.282"
            source: "https://cdn.kernel.org/pub/linux/kernel/v5.x/linux-5.4.282.tar.xz"
          - version: "4.19.320"
            source: "https://cdn.kernel.org/pub/linux/kernel/v4.x/linux-4.19.320.tar.xz"
    steps:
    - uses: actions/checkout@v4
    - run: wget --quiet --output-document kernel.tar.xz ${{ matrix.kernel.source }} && tar xf kernel.tar.xz
    - run: sudo apt-get update && sudo apt-get -y install apt-utils bc lz4 binutils bison build-essential ca-certificates cscope debhelper dwarves flex gcc git libelf-dev libncurses-dev libssl-dev linux-source make openssl pahole perl-base pkg-config python3-debian python-is-python3 rsync vim
    - name: Build kernel
      run: |
        cd linux-${{ matrix.kernel.version }}
        make defconfig
        make kvm_guest.config
        make -j`nproc`
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.4
      with:
        name: bzImage-${{ matrix.kernel.version }}
        path: linux-${{ matrix.kernel.version }}/arch/x86_64/boot/bzImage

    - run: tar cf linux-${{ matrix.kernel.version }}.tar linux-${{ matrix.kernel.version }}

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.4
      with:
        name: all-folder-linux-${{ matrix.kernel.version }}
        path: linux-${{ matrix.kernel.version }}.tar
