name: Kernel Matrix
on:
  push:
  workflow_dispatch:

jobs:
  kernel:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        kernel:
          - version: "6.13-rc7"
            source: "https://git.kernel.org/torvalds/t/linux-6.13-rc7.tar.gz"
          - version: "6.12.9"
            source: "https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.12.9.tar.xz"
          - version: "6.6.71"
            source: "https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.6.71.tar.xz"
          - version: "6.1.124"
            source: "https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.1.124.tar.xz"
          - version: "5.15.176"
            source: "https://cdn.kernel.org/pub/linux/kernel/v5.x/linux-5.15.176.tar.xz"
          - version: "5.10.233"
            source: "https://cdn.kernel.org/pub/linux/kernel/v5.x/linux-5.10.233.tar.xz"
          - version: "5.4.289"
            source: "https://cdn.kernel.org/pub/linux/kernel/v5.x/linux-5.4.289.tar.xz"
    steps:
    - uses: actions/checkout@v4
    - run: wget --quiet --output-document kernel.tar.xz ${{ matrix.kernel.source }} && tar xf kernel.tar.xz
    - run: sudo apt-get update && sudo apt-get -y install apt-utils bc lz4 binutils bison build-essential ca-certificates cscope debhelper dwarves flex gcc git libelf-dev libncurses-dev libssl-dev linux-source make openssl pahole perl-base pkg-config python3-debian python-is-python3 rsync vim
    - name: Build kernel
      run: |
        cd linux-${{ matrix.kernel.version }}
        make defconfig
        make kvm_guest.config
        make -j`nproc`
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.4
      with:
        name: bzImage-${{ matrix.kernel.version }}
        path: linux-${{ matrix.kernel.version }}/arch/x86_64/boot/bzImage
