name: Toybox
on:
  push:
  workflow_dispatch:

jobs:
  toybox:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - run: sudo apt-get update && sudo apt-get -y install autoconf automake autopoint autotools-dev binutils binutils-common binutils-x86-64-linux-gnu bsdextrautils build-essential bzip2 cpp cpp-13 cpp-13-x86-64-linux-gnu cpp-x86-64-linux-gnu debhelper debugedit dh-autoreconf dh-strip-nondeterminism dpkg-dev dwz file g++ g++-13 g++-13-x86-64-linux-gnu g++-x86-64-linux-gnu gcc gcc-13 gcc-13-base gcc-13-x86-64-linux-gnu gcc-x86-64-linux-gnu gettext gettext-base groff-base intltool-debian lto-disabled-list m4 make man-db patch perl perl-modules-5.38 po-debconf rpcsvc-proto xz-utils zip
    - run: git clone --depth=1 https://github.com/landley/toybox
    - run: |
        cd toybox
        export LDFLAGS=--static
        make defconfig
        echo CONFIG_SH=y >> .config
        make toybox
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.4
      with:
        name: toybox
        path: toybox/toybox
  rootfs:
    runs-on: ubuntu-24.04
    needs: [toybox]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/download-artifact@v4
    - run: |
          mkdir rootfs
          pushd rootfs
          mkdir -p usr/{sbin,bin} bin sbin boot
          mkdir -p {dev,etc,home,lib}
          mkdir -p {mnt,opt,proc,srv,sys}
          mkdir -p var/{lib,lock,log,run,spool}
          install -d -m 0750 root
          install -d -m 1777 tmp
          mkdir -p usr/{include,lib,share,src}
          cp ../toybox/toybox usr/bin/toybox
          chmod +x usr/bin/toybox
          for util in $(./usr/bin/toybox --long); do
            ln -s /usr/bin/toybox $util
          done

          popd
          sudo /sbin/mkfs.ext4 -L root -d ./rootfs/ rootfs.ext4 1G

    - run: tar cf rootfs.tar rootfs

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.4
      with:
        name: rootfs-toybox-disk-image
        path: rootfs.ext4
